#    Bank Loan Risk Analysis  #

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("credit_test.csv")
df

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,NaN,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,NaN,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Q1. Find the average current loan amount by home ownership type.

In [3]:
df.groupby('Home Ownership')['Current Loan Amount'].mean()

Home Ownership
HaveMortgage     6.395047e+06
Home Mortgage    1.214183e+07
Own Home         1.054737e+07
Rent             1.123034e+07
Name: Current Loan Amount, dtype: float64

### Q2. Calculate the average credit score for each home ownership type.

In [4]:
df.groupby('Home Ownership')['Credit Score'].mean()

Home Ownership
HaveMortgage      705.090909
Home Mortgage    1029.901423
Own Home         1052.978320
Rent             1139.204405
Name: Credit Score, dtype: float64

### Q-3. Identify customers with credit score below 500.

In [5]:
low_credit = df[df['Credit Score'] < 500]
print(low_credit)

Empty DataFrame
Columns: [Loan ID, Customer ID, Current Loan Amount, Term, Credit Score, Annual Income, Years in current job, Home Ownership, Purpose, Monthly Debt, Years of Credit History, Months since last delinquent, Number of Open Accounts, Number of Credit Problems, Current Credit Balance, Maximum Open Credit, Bankruptcies, Tax Liens]
Index: []

### Q4. Analyse loan amount distribution based on loan term (short-term vs long-term).

In [6]:
df.groupby('Term')['Current Loan Amount'].describe()

,count,mean,std,min,25%,50%,75%,max
Term,,,,,,,,
Long Term,2705.0,8.201928e+06,2.670638e+07,22440.0,319572.0,437228.0,606210.0,99999999.0
Short Term,7295.0,1.286522e+07,3.314511e+07,19470.0,152669.0,243408.0,438900.0,99999999.0

### Q5. Calculate the average annual income of customers.

In [7]:
df['Annual Income'].mean()

np.float64(1369106.0397805213)

### Q6. Count the number of customers in each home ownership category.

In [8]:
df['Home Ownership'].value_counts()

Home Ownership
Home Mortgage    4867
Rent             4203
Own Home          914
HaveMortgage       16
Name: count, dtype: int64

### Q7. Identify customers whose current loan amount is greater than their annual income.

In [9]:
high_loan = df[df['Current Loan Amount'] > df['Annual Income']]
print(high_loan)

                                   Loan ID  \
18    cb6f7b00-62e7-4e18-8e73-73e60396e270
19    e6246fe9-6b7b-448c-a817-f91b58199e32
21    eda0e007-b2b1-486a-b4ce-58adefd6c0bd
86    e840a6a8-28a2-4b38-9863-390381eebee2
112   ce6562c3-f100-4342-8fe8-f03d33ba9ff4
...                                    ...
9972  9265fa56-48fc-4631-8871-8192a7ded692
9978  e1d3aafe-d247-4a0f-9b43-bda8ffa58702
9982  e718c118-1194-4924-bfcb-5711e9a6f140
9998  0cc8e0e0-1bc6-49d7-ad0f-0598b647458f
9999  14f94b64-26c4-48fd-b916-1388d7adcc1d

                               Customer ID  Current Loan Amount        Term  \
18    ce6fc244-b9a8-44b8-95f4-61c41ed5d03b           99999999.0  Short Term
19    bcace9c1-a4c0-4d6d-9582-fa2026c3fc0b           99999999.0   Long Term
21    6518287d-d7df-4cba-8093-4abea80fb718           99999999.0  Short Term
86    2ed5467e-f5ee-4a35-8b86-2df1390672c4           99999999.0  Short Term
112   90192efd-bec5-4f45-b360-a574b3410d33           99999999.0  Short Term
...                                    ...                  ...         ...
9972  f13f7eee-da8c-48a9-987f-4a8bbf71c7a6           99999999.0   Long Term
9978  6dbdc720-ea59-41b3-ab60-f60ba36e26f9           99999999.0  Short Term
9982  d7bd83a7-a27c-4358-b20d-a2fb3c2ae5dd           99999999.0   Long Term
9998  f90cf410-a34b-49e7-8af9-2b405e17b827           99999999.0  Short Term
9999  f1838fa9-7ad9-44d5-97a6-7a6d3f3529d7           99999999.0  Short Term

      Credit Score  Annual Income Years in current job Home Ownership  \
18           715.0       442339.0             < 1 year           Rent
19           715.0       694526.0              8 years           Rent
21           747.0      1394676.0              5 years  Home Mortgage
86           746.0      1132590.0              8 years           Rent
112          749.0      1483881.0              4 years           Rent
...            ...            ...                  ...            ...
9972         670.0      2427250.0              5 years  Home Mortgage
9978         749.0      2290260.0              6 years           Rent
9982         716.0      1592067.0            10+ years       Own Home
9998         721.0       972097.0            10+ years  Home Mortgage
9999         748.0      1079960.0              6 years  Home Mortgage

                 Purpose  Monthly Debt  Years of Credit History  \
18    Debt Consolidation      14007.18                     17.0
19    Debt Consolidation       4358.22                     17.3
21                 Other       5834.33                     31.9
86    Debt Consolidation       8230.23                     22.0
112   Debt Consolidation      15086.19                     22.4
...                  ...           ...                      ...
9972  Debt Consolidation      37824.63                     17.3
9978  Debt Consolidation      35117.32                     15.5
9982  Debt Consolidation      13399.94                     18.1
9998  Debt Consolidation      12232.20                     16.8
9999  Debt Consolidation      12239.61                     19.7

      Months since last delinquent  Number of Open Accounts  \
18                            25.0                     14.0
19                            47.0                      5.0
21                             NaN                      7.0
86                            20.0                      5.0
112                            NaN                     15.0
...                            ...                      ...
9972                           NaN                     15.0
9978                           NaN                      9.0
9982                          26.0                     15.0
9998                          24.0                      8.0
9999                           NaN                     14.0

      Number of Credit Problems  Current Credit Balance  Maximum Open Credit  \
18                          0.0                 65474.0             284966.0
19                          0.0                137332.0             272734.0
21                          0.0                164350.0             569778.0
86                          0.0                298623.0             917180.0
112                         0.0                 65968.0             606210.0
...                         ...                     ...                  ...
9972                        1.0                355338.0             469678.0
9978                        0.0                322050.0             574574.0
9982                        0.0                164730.0             303732.0
9998                        1.0                184984.0             240658.0
9999                        0.0                179018.0             607882.0

      Bankruptcies  Tax Liens
18             0.0        0.0
19             0.0        0.0
21             0.0        0.0
86             0.0        0.0
112            0.0        0.0
...            ...        ...
9972           1.0        0.0
9978           0.0        0.0
9982           0.0        0.0
9998           0.0        0.0
9999           0.0        0.0

[1133 rows x 18 columns]

### Q8. Find the top 10 customers with the highest current loan amount.

In [10]:
top10 = df.sort_values(by='Current Loan Amount', ascending=False).head(10)
print(top10)

                                   Loan ID  \
9999  14f94b64-26c4-48fd-b916-1388d7adcc1d
1529  b352e12f-a97d-4642-b21a-3e055ece3054
865   fde1276a-6e8b-4a4c-b0d0-4cd5bc82f680
864   452f6f26-1a3f-468d-ad9a-4de6f554ca52
6274  00ebbe8a-6170-4a65-a8ee-d992ef7dfc38
6286  ef877891-0329-4f41-8bda-ea1aca2cdfb5
6287  b90a4e17-92b6-4316-bcd6-e214a957bdce
6290  fcb7461d-3bf7-40ee-b208-f49a0dea1652
6291  77b1a86e-67ee-4c36-9acb-7880decf1fe4
1532  742b1457-0340-4de5-95af-9156ab0f2973

                               Customer ID  Current Loan Amount        Term  \
9999  f1838fa9-7ad9-44d5-97a6-7a6d3f3529d7           99999999.0  Short Term
1529  58b55e1c-9ff4-4757-9411-d2bfb2123ea2           99999999.0  Short Term
865   2a707bea-c2f6-4d4e-8ff9-35c1b5abce0c           99999999.0  Short Term
864   48009d40-3850-427d-8669-c66eac4b2dfc           99999999.0  Short Term
6274  8f0a0f62-889e-4e86-905f-c10c3b3f4217           99999999.0  Short Term
6286  e420c3c8-e286-4307-80f7-36305fd27d92           99999999.0  Short Term
6287  3fa23b91-556a-4d0f-8560-911acb46d0f9           99999999.0  Short Term
6290  3b071887-a6b5-4e50-a88d-ff06b196b5d1           99999999.0  Short Term
6291  a03894c7-d981-41ae-a19a-7fa3b8299fe8           99999999.0  Short Term
1532  af284016-5bb4-40ca-ba49-c4135d46fca9           99999999.0   Long Term

      Credit Score  Annual Income Years in current job Home Ownership  \
9999         748.0      1079960.0              6 years  Home Mortgage
1529         738.0      1976969.0              4 years  Home Mortgage
865          738.0      1010914.0              5 years       Own Home
864          747.0       478800.0            10+ years  Home Mortgage
6274         703.0       901493.0              5 years           Rent
6286         731.0      1316168.0            10+ years           Rent
6287         747.0       628444.0               1 year           Rent
6290         661.0      2161839.0              4 years           Rent
6291         731.0      1041333.0            10+ years           Rent
1532         723.0       851751.0               1 year  Home Mortgage

                 Purpose  Monthly Debt  Years of Credit History  \
9999  Debt Consolidation      12239.61                     19.7
1529  Debt Consolidation      28995.52                      8.7
865   Debt Consolidation      13226.09                      6.0
864   Debt Consolidation       7393.47                     19.8
6274               Other      23588.69                     14.0
6286  Debt Consolidation      19084.36                     18.0
6287  Debt Consolidation       7227.03                     15.0
6290  Debt Consolidation      32427.49                     27.9
6291  Debt Consolidation       4130.60                     12.6
1532   Home Improvements      12847.23                     16.2

      Months since last delinquent  Number of Open Accounts  \
9999                           NaN                     14.0
1529                           NaN                     15.0
865                            NaN                     21.0
864                            NaN                     10.0
6274                           NaN                     10.0
6286                           NaN                     13.0
6287                           NaN                      7.0
6290                          31.0                     19.0
6291                           NaN                     10.0
1532                           NaN                     15.0

      Number of Credit Problems  Current Credit Balance  Maximum Open Credit  \
9999                        0.0                179018.0             607882.0
1529                        0.0                290415.0             462550.0
865                         0.0                337022.0            1867206.0
864                         0.0                132886.0             680790.0
6274                        0.0                150233.0             273108.0
6286                        3.0                192546.0             389752.0
6287                        0.0                 17936.0              22044.0
6290                        2.0                164920.0             339790.0
6291                        1.0                 65816.0             423324.0
1532                        1.0                 66196.0             153274.0

      Bankruptcies  Tax Liens
9999           0.0        0.0
1529           0.0        0.0
865            0.0        0.0
864            0.0        0.0
6274           0.0        0.0
6286           0.0        0.0
6287           0.0        0.0
6290           0.0        1.0
6291           1.0        0.0
1532           1.0        0.0

### Q9. Calculate the average credit score based on the loan term.

In [11]:
df.groupby('Term')['Credit Score'].mean()

Term
Long Term     1147.398194
Short Term    1051.503618
Name: Credit Score, dtype: float64

### Q10. Identify high-risk customers based on:
### • Low credit score
### • High monthly debt

In [12]:
high_risk = df[(df['Credit Score'] < 500) & (df["Monthly Debt"] > df['Monthly Debt'].mean()) ]
print(high_risk)

Empty DataFrame
Columns: [Loan ID, Customer ID, Current Loan Amount, Term, Credit Score, Annual Income, Years in current job, Home Ownership, Purpose, Monthly Debt, Years of Credit History, Months since last delinquent, Number of Open Accounts, Number of Credit Problems, Current Credit Balance, Maximum Open Credit, Bankruptcies, Tax Liens]
Index: []